[project]
name = "buddygpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kanchamcloud", email = "kancham.cloud@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "docx2txt>=0.9",
    "duckduckgo-search>=8.1.1",
    "faiss-cpu>=1.15.0",
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "jinja2>=3.1.6",
    "langchain>=1.4.0",
    "langchain-anthropic>=1.7.2",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "langchain-openai>=1.6.2",
    "langchain-tavily>=0.2.18",
    "langchain-text-splitters>=1.1.2",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "openai>=3.13.0",
    "pydantic>=2.13.5",
    "pypdf>=6.18.1",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "streamlit>=1.63.0",
    "tavily-python>=0.8.2",
    "uvicorn>=0.52.4",
    "yfinance>=1.7.0",
]

[project.scripts]
buddygpt = "buddygpt:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
